apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acend-web-ide.fullname" . }}
  labels:
    {{- include "acend-web-ide.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "acend-web-ide.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "acend-web-ide.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "acend-web-ide.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - -c
          - cp -an /tmp/coder/.bashrc /home/coder/.bashrc && cp -an /tmp/coder/.profile
            /home/coder/.profile && cp -an /tmp/coder/.bash_logout /home/coder/.bash_logout
            && dumb-init fixuid -q /usr/bin/code-server --host 0.0.0.0 .
          command:
          - /bin/sh
          env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "acend-web-ide.fullname" . }}"
                key: "{{ .Values.ide.secretKey }}"
          - name: HOME
            value: /home/coder
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: home-dir
              mountPath: /home/coder/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: home-dir
          persistentVolumeClaim:
            claimName: {{ include "acend-web-ide.fullname" . }}
