apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "acend-web-ide.fullname" . }}
  labels:
    {{- include "acend-web-ide.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ide.pvsize }}