---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acend-web-ide.fullname" . }}
  labels:
    {{- include "acend-web-ide.labels" . | nindent 4 }}
data:
  {{ if .Values.ide.password }}
  {{ .Values.ide.secretKey }}: "{{ .Values.ide.password | b64enc }}"
  {{ else }}
  {{ .Values.ide.secretKey }}: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}